#!/usr/bin/env python3
"""Build/check the non-active Mechanism M-069 cold-start release review."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Mapping, Optional, Sequence


REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

from CodexSkills.governance.release.cold_start.review import (  # noqa: E402
    BLOCKER_CODES,
    CANDIDATE_BUNDLE_DIGEST,
    CHANGELOG_PATH,
    COLD_START_HANDOFF_SCHEMA_ID,
    EVIDENCE_INDEX_PATH,
    EVIDENCE_INDEX_SCHEMA_ID,
    EVIDENCE_SPECS,
    FINAL_TASK_ID,
    HUMAN_HANDOFF_PATH,
    INDEX_SELF_POINTER,
    M068_GIT_OBJECT_ID,
    MACHINE_HANDOFF_PATH,
    PROTOCOL_REVISION,
    REVIEW_BASE_GIT_OBJECT_ID,
    SELF_POINTER,
    TASK_PACK_REVISION,
    build_evidence_index,
    build_handoff_core,
    build_machine_handoff,
    validate_evidence_index,
    validate_machine_handoff,
)
from CodexSkills.governance.tools.canonical_json import (  # noqa: E402
    canonical_digest,
    parse_json_bytes,
)
from CodexSkills.governance.tools.validate_au040_semantic_acceptance import (  # noqa: E402
    load_au040_acceptance,
)
from CodexSkills.governance.tools.validate_mechanism import (  # noqa: E402
    ContractBundle,
    ContractError,
    build_registry,
    scan_public_value,
    validate_instance,
)


COLD_START_DIR = (
    REPO_ROOT / "CodexSkills" / "governance" / "release" / "cold_start"
)
SCHEMA_DIR = COLD_START_DIR / "schemas"
EVIDENCE_INDEX_FILE = REPO_ROOT.joinpath(
    *EVIDENCE_INDEX_PATH.split("/")
)
MACHINE_HANDOFF_FILE = REPO_ROOT.joinpath(
    *MACHINE_HANDOFF_PATH.split("/")
)
HUMAN_HANDOFF_FILE = REPO_ROOT.joinpath(*HUMAN_HANDOFF_PATH.split("/"))
CHANGELOG_FILE = REPO_ROOT.joinpath(*CHANGELOG_PATH.split("/"))
EVIDENCE_INDEX_SCHEMA_FILE = (
    SCHEMA_DIR / "mechanism-evidence-index.schema.json"
)
COLD_START_HANDOFF_SCHEMA_FILE = (
    SCHEMA_DIR / "cold-start-handoff.schema.json"
)
VERSION_PATH = REPO_ROOT / "CodexSkills" / "VERSION"
COMMON_REF = (
    "urn:linzecolin:agentdatabase:skillops:"
    "schema:common-definitions:v1#/$defs/"
)

MILESTONES = (
    (
        "RELEASE_FOUNDATION",
        "sha1:27d93b4ab24cbb88a35412fa969821bc46ae8674",
        "Task Pack provenance, SRV separation, and policy conflict gates",
    ),
    (
        "FINAL_CANDIDATE",
        "sha1:5ee37d7499c62ec19381dac7eb95cb12743ad2d5",
        "31 schemas / 5 policies materialized as CANDIDATE",
    ),
    (
        "CONSUMER_FIRST",
        "sha1:91a12e48351be3ee05ec23ef61aec81056b02014",
        "daily-ledger consumer ready; canonical publication remains false",
    ),
    (
        "BOUND_RESOLVER_AND_REGISTRY",
        "sha1:98e193e74991346d266bdd94ae720c32f25dfb47",
        "registered 89-root snapshot and non-active resolver evidence",
    ),
    (
        "VERSION_POLICY_V3_CONSUMER",
        "sha1:0348e0bda8ca381bbdaca5d86a7c2ddfdc4b685f",
        "Mechanism dual-read ready; schedule authority unresolved",
    ),
    (
        "CONTROLLED_ITERATION",
        "sha1:36ce92ddaf2f5cde5b027317e1aaf21bc0f019db",
        "promotion/rollback/freshness/evaluator-protection chain closed",
    ),
    (
        "RETENTION_AND_MIGRATION",
        "sha1:0b59768ed3697a1cd3c93afda70d96b9034f99ef",
        "72h/365d/disclosure and read-only cutover evidence closed",
    ),
    (
        "OPERATIONS",
        "sha1:9f7cebdcdeae54c0732f73d8bf8ce11690f4145b",
        "capacity budgets and actionable dashboard evidence ready",
    ),
    (
        "FAILURE_TO_TEST",
        "sha1:6cf5beae7c50c3fb860926df670dcc5fc33890e3",
        "confirmed-failure to regression Shadow conversion closed",
    ),
    (
        "REPRESENTATIVE_PILOTS",
        M068_GIT_OBJECT_ID,
        "three pilots / nine stable Shadow cycles / nine rollback drills",
    ),
)


class ColdStartBuildError(ValueError):
    """M-069 source, generated byte, schema, or trust closure failed."""


def _sha256(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _render_json(value: Mapping[str, Any]) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")


def _load(raw: bytes, code: str) -> Mapping[str, Any]:
    try:
        value = parse_json_bytes(raw)
    except Exception as exc:
        raise ColdStartBuildError(code) from exc
    if not isinstance(value, dict):
        raise ColdStartBuildError(code)
    return value


def _git_blob(tagged_object: str, relative_path: str) -> bytes:
    if (
        not tagged_object.startswith("sha1:")
        or len(tagged_object) != 45
    ):
        raise ColdStartBuildError("M069_GIT_OBJECT_INVALID")
    process = subprocess.run(
        [
            "git",
            "-C",
            str(REPO_ROOT),
            "show",
            tagged_object[5:] + ":" + relative_path,
        ],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=20,
        check=False,
    )
    if process.returncode != 0:
        raise ColdStartBuildError(
            "M069_GIT_BLOB_UNAVAILABLE:" + relative_path
        )
    return process.stdout


def _is_ancestor(older: str) -> bool:
    process = subprocess.run(
        [
            "git",
            "-C",
            str(REPO_ROOT),
            "merge-base",
            "--is-ancestor",
            older[5:],
            "HEAD",
        ],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        timeout=20,
        check=False,
    )
    return process.returncode == 0


def _current(relative_path: str) -> bytes:
    path = REPO_ROOT.joinpath(*relative_path.split("/"))
    if not path.is_file() or path.is_symlink():
        raise ColdStartBuildError(
            "M069_CURRENT_FILE_INVALID:" + relative_path
        )
    return path.read_bytes()


def _source_material():
    if not _is_ancestor(REVIEW_BASE_GIT_OBJECT_ID):
        raise ColdStartBuildError("M069_REVIEW_BASE_NOT_ANCESTOR")
    raw_documents = {}
    for spec in EVIDENCE_SPECS:
        source_raw = _git_blob(
            spec.source_git_object_id,
            spec.path,
        )
        review_raw = _git_blob(REVIEW_BASE_GIT_OBJECT_ID, spec.path)
        current_raw = _current(spec.path)
        if (
            source_raw != review_raw
            or review_raw != current_raw
            or _sha256(source_raw) != spec.content_digest
        ):
            raise ColdStartBuildError(
                "M069_SOURCE_BYTE_DRIFT:" + spec.code
            )
        _load(source_raw, "M069_SOURCE_JSON_INVALID:" + spec.code)
        raw_documents[spec.code] = source_raw
    return raw_documents


def _constant_schema(
    schema_id: str,
    value: Mapping[str, Any],
    digest_field: str,
    title: str,
) -> Mapping[str, Any]:
    properties = {
        key: {"const": item}
        for key, item in value.items()
        if key != digest_field
    }
    properties[digest_field] = {"$ref": COMMON_REF + "sha256"}
    return {
        "$id": schema_id,
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": False,
        "properties": properties,
        "required": list(value),
        "title": title,
        "type": "object",
    }


def _extend_bundle(
    base: ContractBundle,
    additions: Mapping[str, Mapping[str, Any]],
    pointers: Mapping[str, str],
) -> ContractBundle:
    schemas = dict(base.schemas)
    self_pointers = dict(base.self_digest_pointers)
    for schema_id, schema in additions.items():
        if schema_id in schemas:
            raise ColdStartBuildError(
                "M069_SCHEMA_REBIND_FORBIDDEN:" + schema_id
            )
        schemas[schema_id] = schema
        self_pointers[schema_id] = pointers[schema_id]
    try:
        registry, checker = build_registry(schemas)
    except ContractError as exc:
        raise ColdStartBuildError(
            "M069_SCHEMA_CLOSURE_INVALID:" + str(exc)
        ) from exc
    return ContractBundle(
        schemas=schemas,
        registry=registry,
        format_checker=checker,
        self_digest_pointers=self_pointers,
        policies=base.policies,
        protocol_revision=base.protocol_revision,
    )


def _render_handoff(
    core: Mapping[str, Any],
    index: Mapping[str, Any],
) -> bytes:
    state = core["current_state"]
    validation = core["validation_baseline"]
    lines = [
        "# SkillOps Mechanism cold-start handoff",
        "",
        "Status: "
        "`DRAFT_NON_ACTIVE_MECHANISM_TASKPACK_RELEASE_REVIEW_"
        "COMPLETE_WITH_BLOCKERS`",
        "",
        "This is the canonical human cold-start entry for Mechanism Task Pack "
        "v0.0.0.2.",
        "The pack ends at M-069; there is no M-070. A new agent can recover "
        "the exact",
        "state from this repository without chat history by running:",
        "",
        "```bash",
        "/usr/bin/python3 -B \\",
        "  CodexSkills/governance/tools/"
        "build_cold_start_release_review.py --check",
        "/usr/bin/python3 -B -m unittest \\",
        "  CodexSkills.governance.tests.test_cold_start_release_review",
        "```",
        "",
        "## Exact trust roots",
        "",
        f"- Reviewed predecessor: `{REVIEW_BASE_GIT_OBJECT_ID}`",
        f"- Candidate bundle: `{CANDIDATE_BUNDLE_DIGEST}` "
        "(31 schemas / 5 policies / CANDIDATE)",
        f"- Evidence index: `{EVIDENCE_INDEX_PATH}`",
        f"- Evidence index self digest: `{index['index_digest']}`",
        "- Repository self-report is not a trust root; the builder verifies "
        "every indexed",
        "  path against its external Git object and the reviewed predecessor.",
        "",
        "## Current truthful state",
        "",
        f"- Registry Identity/Instance/Version: "
        f"`{state['registry_identity_count']}/"
        f"{state['registry_instance_count']}/"
        f"{state['registry_version_count']}`; binding-eligible: "
        f"`{state['binding_eligible_version_count']}`.",
        f"- Registered snapshot vs current mirror instances: "
        f"`{state['registry_instance_count']}/"
        f"{state['repository_mirror_skill_instance_count']}`; parity: "
        "`false`.",
        "- Representative pilots: `3` pilots / `9` stable metadata-only "
        "Shadow cycles",
        "  / `9` synthetic rollback drills; no production pilot ran.",
        "- Schedule authority remains unresolved between `04:15` and `05:30` "
        "Australia/Sydney.",
        "- `CodexSkills/VERSION` is absent. ACTIVE trust, runtime state, "
        "canonical",
        "  shards/publication, Gmail readiness, migration, and activation "
        "remain false.",
        "- M-069 completes the Task Pack review artifact, not production "
        "activation.",
        "",
        "## Known fail-closed blockers",
        "",
        *[f"- `{code}`" for code in BLOCKER_CODES],
        "",
        "## Last accepted validation baseline",
        "",
        f"- M-068 target: "
        f"`{validation['targeted_m068_tests']['tests_run']}/"
        f"{validation['targeted_m068_tests']['tests_run']} PASS`",
        f"- Complete Mechanism before M-069: "
        f"`{validation['complete_mechanism']['tests_run']}/"
        f"{validation['complete_mechanism']['tests_run']} PASS`",
        "- Schema sets: `21 / 41 / 24 / 85`; candidate trust: `31 / 5`.",
        "- OpenAIDatabase consumer: `23/23 PASS`; canonical publication=false.",
        "- Auto transition baseline: `200 tests / 5 failures / 20 errors`.",
        "- Fault/privacy seeds 271828 and 314159: each "
        "`149 / 5 failures / 25 errors`.",
        "",
        "## Stop condition and next action",
        "",
        "Mechanism development stops after M-069 remote readback. No further "
        "Mechanism",
        "Task Pack phase exists. Do not activate, publish, create VERSION, "
        "change schedule,",
        "repair Auto-owned files, or call a development verifier. The only "
        "next action is:",
        "",
        "`OWNER_SELECT_AND_RUN_FRESH_VERIFIER`",
        "",
        "The machine handoff is at "
        f"`{MACHINE_HANDOFF_PATH}`; the release changelog is at "
        f"`{CHANGELOG_PATH}`.",
        "",
    ]
    return ("\n".join(lines)).encode("utf-8")


def _render_changelog(
    core: Mapping[str, Any],
    index: Mapping[str, Any],
) -> bytes:
    del core
    lines = [
        "# SkillOps Mechanism changelog",
        "",
        "Status: `DRAFT_NON_ACTIVE`",
        "",
        "No SRV was allocated and `CodexSkills/VERSION` remains absent. "
        "This changelog",
        "records non-active Mechanism implementation evidence only.",
        "",
        "## M-069 — cold-start Handoff and release review",
        "",
        "- Added a validated machine Handoff, human cold-start Handoff, and "
        "exact evidence index.",
        "- Recorded Task Pack completion through its actual final task M-069; "
        "no M-070 exists.",
        "- Preserved every production, schedule, Auto, Gmail/state, ACTIVE, "
        "publication, migration, and activation blocker.",
        "- Stopped before an Owner-selected fresh verifier.",
        "",
        "## Immutable implementation milestones",
        "",
        "| Milestone | Git object | Evidence outcome |",
        "|---|---|---|",
    ]
    lines.extend(
        f"| `{code}` | `{object_id}` | {outcome} |"
        for code, object_id, outcome in MILESTONES
    )
    lines.extend(
        [
            "",
            "## Evidence closure",
            "",
            f"- Index entries: `{len(index['entries'])}`",
            f"- Index self digest: `{index['index_digest']}`",
            f"- Reviewed predecessor: `{REVIEW_BASE_GIT_OBJECT_ID}`",
            f"- Candidate bundle digest: `{CANDIDATE_BUNDLE_DIGEST}`",
            "- Canonical publication / activation / VERSION: "
            "`false / false / absent`",
            "",
        ]
    )
    return ("\n".join(lines)).encode("utf-8")


def _documents() -> Mapping[Path, bytes]:
    source_documents = _source_material()
    index = build_evidence_index(source_documents)
    validate_evidence_index(index, source_documents)
    core = build_handoff_core(index)
    human_raw = _render_handoff(core, index)
    changelog_raw = _render_changelog(core, index)
    handoff = build_machine_handoff(
        index,
        _sha256(human_raw),
        _sha256(changelog_raw),
    )
    validate_machine_handoff(
        handoff,
        index,
        _sha256(human_raw),
        _sha256(changelog_raw),
    )
    index_schema = _constant_schema(
        EVIDENCE_INDEX_SCHEMA_ID,
        index,
        "index_digest",
        "Mechanism M-069 evidence index",
    )
    handoff_schema = _constant_schema(
        COLD_START_HANDOFF_SCHEMA_ID,
        handoff,
        "artifact_digest",
        "Mechanism M-069 cold-start Handoff",
    )
    contract = _extend_bundle(
        load_au040_acceptance().bundle,
        {
            EVIDENCE_INDEX_SCHEMA_ID: index_schema,
            COLD_START_HANDOFF_SCHEMA_ID: handoff_schema,
        },
        {
            EVIDENCE_INDEX_SCHEMA_ID: INDEX_SELF_POINTER,
            COLD_START_HANDOFF_SCHEMA_ID: SELF_POINTER,
        },
    )
    if len(contract.schemas) != 33 or len(contract.policies) != 5:
        raise ColdStartBuildError("M069_SCHEMA_OR_POLICY_COUNT_INVALID")
    validate_instance(
        contract,
        index,
        EVIDENCE_INDEX_SCHEMA_ID,
        expected_bundle_digest=CANDIDATE_BUNDLE_DIGEST,
        verify_digest=True,
        public=True,
    )
    validate_instance(
        contract,
        handoff,
        COLD_START_HANDOFF_SCHEMA_ID,
        expected_bundle_digest=CANDIDATE_BUNDLE_DIGEST,
        verify_digest=True,
        public=True,
    )
    scan_public_value(index, contract.policies)
    scan_public_value(handoff, contract.policies)
    return {
        EVIDENCE_INDEX_FILE: _render_json(index),
        MACHINE_HANDOFF_FILE: _render_json(handoff),
        HUMAN_HANDOFF_FILE: human_raw,
        CHANGELOG_FILE: changelog_raw,
        EVIDENCE_INDEX_SCHEMA_FILE: _render_json(index_schema),
        COLD_START_HANDOFF_SCHEMA_FILE: _render_json(handoff_schema),
    }


def _write() -> None:
    for path, raw in _documents().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(raw)


def _check() -> None:
    for path, expected in _documents().items():
        if not path.is_file() or path.is_symlink():
            raise ColdStartBuildError(
                "M069_GENERATED_FILE_INVALID:" + str(path)
            )
        if path.read_bytes() != expected:
            raise ColdStartBuildError(
                "M069_GENERATED_BYTE_DRIFT:" + str(path)
            )
    if VERSION_PATH.exists():
        raise ColdStartBuildError("M069_VERSION_MUST_REMAIN_ABSENT")


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.write:
            _write()
        else:
            _check()
        index = _load(
            _documents()[EVIDENCE_INDEX_FILE],
            "M069_INDEX_INVALID",
        )
        print(
            "COLD_START_RELEASE_REVIEW_OK task="
            + FINAL_TASK_ID
            + " evidence="
            + str(len(index["entries"]))
            + " chat_required=false production_ready=false "
            "next=OWNER_SELECT_AND_RUN_FRESH_VERIFIER"
        )
        return 0
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
